on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: self-hosted
    name: Deploy to DETI machine
    env:
      PRODUCTION: true
      CURRENCY_API_KEY: ${{secrets.CURRENCY_API_KEY}}
      JWT_PRIVATE: ${{secrets.JWT_PRIVATE}}
      JWT_PUBLIC: ${{secrets.JWT_PUBLIC}}
      POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
      HOST_URL: deti-tqs-16.ua.pt
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to GitHub Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy with Docker Compose
        run: |
          docker compose -f compose.prod.yaml pull
          docker compose -f compose.prod.yaml up -d --remove-orphans
          docker container prune -f
          docker image prune -af
          docker builder prune -af
